---- nvim-dap-ui
----------------------------------------------------------------------
----variables
--local dap = require("dap")
--local dapui = require("dapui")
----------------------------------------------------------------------
--dapui.setup({
--    controls = {
--        element = "repl",
--        enabled = true,
--        icons = {
--            disconnect = "󱐤",
--            run_last = "󰑙",
--            terminate = "",
--            pause = "󰏤",
--            play = "",
--            step_into = "󰆹",
--            step_out = "󰆸",
--            step_over = "󰆷",
--            step_back = "󰓕",
--        },
--    },
--    floating = {
--        border = "single",
--        mappings = {
--            close = { "q", "<Esc>" },
--        },
--    },
--    icons = { collapsed = "", expanded = "", current_frame = "" },
--    layouts = {
--        {
--            elements = {
--                { id = "stacks",      size = 0.25 },
--                { id = "scopes",      size = 0.25 },
--                { id = "breakpoints", size = 0.25 },
--                { id = "watches",     size = 0.25 },
--            },
--            position = "left",
--            size = 60,
--        },
--        {
--            elements = {
--                { id = "repl", size = 1.0 },
--            },
--            position = "bottom",
--            size = 10,
--        },
--    },
--})
----------------------------------------------------------------------

--dap.listeners.after.event_initialized["dapui_config"] = function()
--    dapui.open()
--end -- after the debugger is initialized, run this lua function to open the UI

--dap.listeners.before.event_terminated["dapui_config"] = function()
--    dapui.close()
--end -- run this lua function after the debugger terminates to close the UI

--dap.listeners.before.event_exited["dapui_config"] = function()
--    dapui.close()
--end -- run this lua function after the debug exits to close the UI
